# Generated by Django 6.0.5 on 2026-05-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('home_type', models.CharField(choices=[('apartment', 'Kvartira'), ('house', 'Uy'), ('studio', 'Studiya'), ('villa', 'Villa'), ('office', 'Ofis'), ('commercial', 'Tijorat')], max_length=20)),
                ('area', models.FloatField(help_text='Kvadrat metr')),
                ('rooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('floors', models.IntegerField(default=1)),
                ('repair_type', models.CharField(choices=[('cosmetic', 'Kosmetik remont'), ('euro', 'Evro remont'), ('design', 'Dizayn remont'), ('premium', 'Premium remont'), ('full', 'Kapital remont')], default='euro', max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Rejalashtirilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('on_hold', 'Kutmoqda')], default='planning', max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('has_smart_home', models.BooleanField(default=False)),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
                ('progress', models.IntegerField(default=0, help_text='0-100%')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
