# Generated by Django 6.0.5 on 2026-05-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('electrician', 'Elektrik'), ('designer', 'Dizayner'), ('plumber', 'Santexnik'), ('renovator', 'Remontchi'), ('carpenter', 'Mebelsoz'), ('smart_home', 'Smart-home ustasi'), ('painter', "Bo'yoqchi"), ('tiler', 'Kafelchi')], max_length=20)),
                ('experience_years', models.IntegerField(default=1)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('bio', models.TextField()),
                ('portfolio_images', models.JSONField(default=list)),
                ('phone', models.CharField(max_length=20)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(default='Toshkent', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usta Profil',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Kutmoqda'), ('accepted', 'Qabul qilindi'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_orders', to='marketplace.masterprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.masterprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.order')),
            ],
        ),
    ]
