# Generated by Django 6.0.5 on 2026-05-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Smeta', max_length=200)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('electrical_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('furniture_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('design_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('smart_home_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('items', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smeta',
                'verbose_name_plural': 'Smetalar',
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('labor', 'Ish haqi'), ('material', 'Material'), ('electrical', 'Elektr'), ('furniture', 'Mebel'), ('plumbing', 'Santexnika'), ('smart_home', 'Smart Home'), ('other', 'Boshqa')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(default='dona', max_length=20)),
                ('quantity', models.FloatField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_items', to='estimates.estimate')),
            ],
        ),
    ]
