# Generated by Django 6.0.5 on 2026-05-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preview_image', models.ImageField(blank=True, upload_to='styles/')),
                ('prompt_template', models.TextField(help_text='AI prompt template')),
            ],
        ),
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_design.aichat')),
            ],
        ),
        migrations.CreateModel(
            name='AIDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(default='living_room', max_length=50)),
                ('style', models.CharField(default='modern', max_length=50)),
                ('area', models.FloatField(default=30)),
                ('color_scheme', models.CharField(default='neutral', max_length=100)),
                ('budget_level', models.CharField(default='medium', max_length=20)),
                ('custom_prompt', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai_designs/')),
                ('image_url', models.URLField(blank=True)),
                ('ai_response', models.TextField(blank=True)),
                ('color_palette', models.JSONField(default=list)),
                ('furniture_suggestions', models.JSONField(default=list)),
                ('material_suggestions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Kutmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tayyor'), ('failed', 'Xato')], default='pending', max_length=20)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('prompt_used', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Dizayn',
                'ordering': ['-created_at'],
            },
        ),
    ]
