name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/domiq_ai
          
          # Yangi kodni yuklab olish
          git reset --hard HEAD
          git pull origin main
          
          # Virtual muhitni faollashtirish va kutubxonalarni yangilash
          source venv/bin/activate
          pip install -r requirements.txt
          
          # Django sozlamalarini yangilash
          python manage.py migrate
          python manage.py collectstatic --noinput
          
          # Serverni qayta ishga tushirish (Daphne service)
          sudo systemctl restart domiq
