# Generated by Django 6.0.5 on 2026-05-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_plan_image', models.ImageField(blank=True, null=True, upload_to='electrical/')),
                ('area', models.FloatField(default=50)),
                ('rooms', models.IntegerField(default=3)),
                ('has_smart_home', models.BooleanField(default=False)),
                ('sockets_count', models.IntegerField(default=0)),
                ('switches_count', models.IntegerField(default=0)),
                ('lights_count', models.IntegerField(default=0)),
                ('cable_length', models.FloatField(default=0)),
                ('circuit_breakers', models.IntegerField(default=0)),
                ('socket_positions', models.JSONField(default=list)),
                ('switch_positions', models.JSONField(default=list)),
                ('light_positions', models.JSONField(default=list)),
                ('smart_home_devices', models.JSONField(default=list)),
                ('ai_analysis', models.TextField(blank=True)),
                ('recommendations', models.JSONField(default=list)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Kutmoqda'), ('analyzing', 'Tahlil qilinmoqda'), ('completed', 'Tayyor'), ('failed', 'Xato')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_plans', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elektr Reja',
                'verbose_name_plural': 'Elektr Rejalar',
            },
        ),
    ]
